- name: Build
      run: |
        go build -o nanosharp main.go
        ls -la

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-binary
        path: ./nanosharp
