name: Build Go Binary

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Build Binary
        run: |
          go build -o nanosharp .
          ls -la nanosharp

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nanosharp-binary
          path: nanosharp
